// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.6.1
// source: debug/serviceoutput.proto

package pb_debug

import (
	pb_systemmanager_messages "ase/pb_systemmanager_messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// When the debug transceiver picks up a SensorOutput message, it will wrap it in a DebugSensorOutput message,
// so that the receiver can determine from which process the message originated
type DebugServiceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  *pb_systemmanager_messages.ServiceIdentifier `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`   // The service that sent the message
	Address string                                       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // The service output address
	SentAt  int64                                        `protobuf:"varint,4,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	Message []byte                                       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DebugServiceMessage) Reset() {
	*x = DebugServiceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_debug_serviceoutput_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugServiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugServiceMessage) ProtoMessage() {}

func (x *DebugServiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_debug_serviceoutput_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugServiceMessage.ProtoReflect.Descriptor instead.
func (*DebugServiceMessage) Descriptor() ([]byte, []int) {
	return file_debug_serviceoutput_proto_rawDescGZIP(), []int{0}
}

func (x *DebugServiceMessage) GetSender() *pb_systemmanager_messages.ServiceIdentifier {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *DebugServiceMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DebugServiceMessage) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *DebugServiceMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_debug_serviceoutput_proto protoreflect.FileDescriptor

var file_debug_serviceoutput_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x24, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9b, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x74, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0e,
	0x5a, 0x0c, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x62, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_debug_serviceoutput_proto_rawDescOnce sync.Once
	file_debug_serviceoutput_proto_rawDescData = file_debug_serviceoutput_proto_rawDesc
)

func file_debug_serviceoutput_proto_rawDescGZIP() []byte {
	file_debug_serviceoutput_proto_rawDescOnce.Do(func() {
		file_debug_serviceoutput_proto_rawDescData = protoimpl.X.CompressGZIP(file_debug_serviceoutput_proto_rawDescData)
	})
	return file_debug_serviceoutput_proto_rawDescData
}

var file_debug_serviceoutput_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_debug_serviceoutput_proto_goTypes = []interface{}{
	(*DebugServiceMessage)(nil),                         // 0: protobuf_msgs.DebugServiceMessage
	(*pb_systemmanager_messages.ServiceIdentifier)(nil), // 1: protobuf_msgs.ServiceIdentifier
}
var file_debug_serviceoutput_proto_depIdxs = []int32{
	1, // 0: protobuf_msgs.DebugServiceMessage.sender:type_name -> protobuf_msgs.ServiceIdentifier
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_debug_serviceoutput_proto_init() }
func file_debug_serviceoutput_proto_init() {
	if File_debug_serviceoutput_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_debug_serviceoutput_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugServiceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_debug_serviceoutput_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_debug_serviceoutput_proto_goTypes,
		DependencyIndexes: file_debug_serviceoutput_proto_depIdxs,
		MessageInfos:      file_debug_serviceoutput_proto_msgTypes,
	}.Build()
	File_debug_serviceoutput_proto = out.File
	file_debug_serviceoutput_proto_rawDesc = nil
	file_debug_serviceoutput_proto_goTypes = nil
	file_debug_serviceoutput_proto_depIdxs = nil
}
